### ISSUE TITLE
Obsoleting 'anatomical cluster'

### ISSUE THREAD

**Issue by sebastianduesing** [PhiBabs935/IDO-FLU#1]
_Anatomical cluster_ (UBERON_0000477) seems like it should be obsoleted in favor of the CARO _anatomical entity_ branch. There are significant issues with Uberon's own organization of that class; _anatomical cluster_ is defined as a type of anatomical group, but Uberon doesn't place _anatomical cluster_ within the _anatomical group_ class (_anatomical group_ is actually a subclass of a subclass of a sibling class of _anatomical cluster_).

I have an issue open [here](https://github.com/obophenotype/uberon/issues/2491) about that organization issue, but in the meantime, because Uberon itself doesn't even have a coherent hierarchy into which _anatomical cluster_ fits, it's going to be messy to try to link _anatomical cluster_ with anything else in FLU.

If there's a need for the _anatomical cluster_ class—not sure about that yet, I'm going to do some reading and try to figure out how much that term actually comes up in flu literature—it may be preferable to try to find an alternative, comparable term from a different ontology or, in the absence of an alternative, create one. At the moment, I'm not certain if there is an alternative, but I'll add a comment here if I find one.

**Comment by sebastianduesing** [comment]
After some further research, it seems like _anatomical cluster_ is not a particularly commonly-used term outside of ontology, but there are a few instances of its use in papers. None of those instances were flu-related, and only a couple of them were even virus-related. I think it's safe to obsolete _anatomical cluster_ from IDOFLU for now. If, later on, that term becomes relevant in flu literature, it may be best to create an analogous class under the _fiat object part_ class if Uberon's hierarchy hasn't been fixed at that point.

**Comment by PhiBabs935** [comment]
So, there is a editor's note for the term anatomical cluster saying it is marked for obsoletion, but this links to an old, and closed issue from 2014: https://github.com/obophenotype/caro/issues/3

The issue is that the term is widely used, so they needed a replacement term for the ontologies using it. 

That said, since there is currently nothing asserted as a subclass of the term in IDOFLU I agree it is safe to remove it for now.

**Comment by sebastianduesing** [comment]
Hmm. Noted. Thanks for pointing out the closed issue from CARO; I didn't find that on my initial search. Will obsolete it in a future pull request.
