### ISSUE TITLE
Processes 'health care process', 'treatment', etc

### ISSUE THREAD

**Issue by sebastianduesing** [PhiBabs935/IDO-FLU#2]
FLU currently includes 'health care process' from OGMS as a subclass of planned process, with the definition "A planned process with the objective to improve the health status of a patient that directly involves the treatment, diagnosis, or prevention of disease or injury of a patient". This definition suggests a logical relation between 'health care process' and treatment, diagnosis, or prevention, but I think the nature of the relation there is unclear, depending on whether the "or" in "treatment, diagnosis, or prevention" is assumed to be inclusive or exclusive. If inclusive, then treatment, diagnosis, and prevention would each have a part_of relationship to 'health care process'. If it's exclusive and each health care process can only include one of them, then I'd think there's an is_a relationship there.

The main reason why I think this is worth figuring out is because of the organization of 'treatment', etc., in the hierarchy. In FLU, 'treatment' is currently a sibling class of 'health care process', though OGMS has re-organized 'treatment' to be a subclass of 'health care process'. I think for now it's best to follow OGMS's placement of 'treatment'. FLU also includes 'disorder treatment' as a sibling class of 'planned process', which should probably be made a subclass of 'treatment'.

This is all really broad in scope for FLU. As I'm writing this I'm thinking this would probably be best passed along to VIDO-- as far as I can tell, none of these terms are currently in VIDO.

**Comment by PhiBabs935** [comment]
Ah, that's just something that I never noticed before when I was fixing up the last publicly released version a year ago. I hadn't intentionally placed it that way. 

The last version of FLU (not my update) was from 2015, and I just never updated that term's placement. Good catch!

**Comment by PhiBabs935** [comment]
I also missed 'disorder treatment'. 

That was imported from the Vaccine Ontology (VO), and surprisingly OGMS's 'treatment' isn't even in VO. (Hence why it ended up imported here as a subclass of process. I agree it should be moved. But that is also a VO issue.
